import {listPatients,resolvePatient,patientStatements} from "@/lib/patient-db";
import {db,insertRecord,normalize} from "@/lib/clinic-db";
import {recordSchema} from "@/lib/clinic";
import {repeatMessage} from "@/lib/vaccine-spacing";
import {headers} from "next/headers";
import {githubWorkspace} from "@/lib/github-context";
export async function workspace(){return githubWorkspace()||(await headers()).get("oai-authenticated-user-id")||"local-demo";}
export async function GET(){try{const w=await workspace();const rows=await db().prepare("SELECT * FROM records WHERE workspace=? AND patient_id NOT LIKE 'TEST-%' ORDER BY date DESC,name").bind(w).all();const run=await db().prepare("SELECT report FROM runs WHERE workspace=? ORDER BY created DESC LIMIT 1").bind(w).first<{report:string}>();return Response.json({records:rows.results.map(normalize),patients:await listPatients(w),report:run?JSON.parse(run.report):null},{headers:{"Cache-Control":"no-store"}});}catch(e){console.error(e);return Response.json({error:"Records could not be loaded. Please try again."},{status:503});}}
export async function POST(req:Request){try{const payload:any=await req.json(),w=await workspace();
const firstName=typeof payload.firstName==="string"?payload.firstName.trim():"",lastName=typeof payload.lastName==="string"?payload.lastName.trim():"";
const patientId=await resolvePatient(w,firstName+" "+lastName,typeof payload.dob==="string"?payload.dob:"",payload.patientId);
const r=recordSchema.safeParse({...payload,location:typeof payload.city==="string"&&typeof payload.state==="string"?payload.city.trim()+", "+payload.state:"",patientId,firstName,lastName,name:firstName+" "+lastName});if(!r.success)return Response.json({error:"Complete all required fields, including birthdate, home address, a valid phone number and email. Birthdate cannot be in the future."},{status:400});const result=await insertRecord(w,r.data,true);if(result.meta.changes===0)return Response.json({error:repeatMessage,code:"VACCINE_TOO_SOON"},{status:409});await db().batch(patientStatements(w,r.data));return Response.json({ok:true,patientId},{status:201});}catch(e){if(String(e).includes("PATIENT_MISMATCH"))return Response.json({error:"The name and date of birth must match the selected patient."},{status:400});if(String(e).includes("UNIQUE"))return Response.json({error:"Possible duplicate: this patient, vaccine, date and dose already exist. Review the existing record; nothing was removed."},{status:409});console.error(e);return Response.json({error:"Record could not be saved. Your form is still available; please retry."},{status:503});}}
